### ISSUE TITLE
Incorrect text wrapping on the 'continue' button on the password screen for the Vault

### ISSUE THREAD

**Issue by koamedev** [Kin69/EasyNotes#110]
Clicking the Vault button brings up a screen where you input the password.

If the screen's width is too small the text on the continue button will wrap characters to the next line (it's even worse with other languages). If the screen is too wide, the button becomes unnecessarily wide too.

I suggest matching the button's width to the width of the label.

![Screenshot_20240717_164217_Easy Notes](https://github.com/user-attachments/assets/67b2f497-da3b-49e3-9611-b6ffc3de301a)

![Screenshot_20240717_170801_Easy Notes](https://github.com/user-attachments/assets/43eb68bf-7271-4648-9b67-3d6aa2dac340)

I'm not very familiar with Compose but when I get this project to build on my PC I might make a pull request for a fix.

I was unsure if I should tag this as a bug, so:
### Smartphone Information
- **Device:** Samsung Galaxy M23 5G (SM-M236B/DS)
- **OS:** Android 14
- **EasyNotes Version:** 1.3 and the nightly build

**Comment by Kin69** [comment]
Thanks for the feedback! I've addressed the button width issue in the latest nightly build. You can test the updated version here: [Nightly Easy Notes](https://github.com/Kin69/EasyNotes/releases/download/Nightly/EasyNotes-nightly.apk). Your input helps us improve the app—let us know if you encounter any more issues!
