### ISSUE TITLE
Add undo and redo button

### ISSUE THREAD

**Issue by Zyqthrlx** [Kin69/EasyNotes#115]
It's quite frustrating when you select all the text and accidentally deleted it and there's no redo or undo button to fix that problem.

Hoping that these feature should be added!! Overall this is now my go to note app^⁠^

**Comment by Kin69** [comment]
It’s great to hear that you’re enjoying app. The good news is that the undo/redo feature has been implemented in the nightly build. You can try it out by downloading the latest version from this link: [Nightly Easy Notes](https://github.com/Kin69/EasyNotes/releases/download/Nightly/EasyNotes-nightly.apk). Hopefully, this update makes your experience even better!
