### ISSUE TITLE
Some enhancements in crypto addresses (donations)

### ISSUE THREAD

**Issue by serrq** [Kin69/EasyNotes#117]
You just showed the network, but forgot to specifying the token you want.
This is the proper wrote:

Network                    /                     Token

• Binance Smart Chain (BSC)       BNB
• Tron                                                TRX
• Polygon                                          MATIC
• Avalanche                                      AVAX
• Ethereum                                       ETH

Otherwise people don’t know what to send you.

![1000115842](https://github.com/user-attachments/assets/f623104d-feff-406b-9331-e74fc64441b1)

**Comment by Kin69** [comment]
i probbably don't i will add it

**Comment by Kin69** [comment]
Yes, @serrq, it is as you said. I will update it
