### ISSUE TITLE
Similarity, or... something else?

### ISSUE THREAD

**Issue by derei** [Kin69/EasyNotes#122]
I just found this... and it looks shockingly similar in some aspects.
https://github.com/Swatian/nexnotes?tab=readme-ov-file

**Comment by Kin69** [comment]
They copied the entire app design but rewrote it in Java. They should have asked for permission or at least mentioned EasyNotes. While they may not have violated the GPL, their approach lacks the proper acknowledgment and collaboration the license encourages.

**Comment by aRandomMenno** [comment]
Make an issue on that repo, lets see if it gets deleted :)

**Comment by aRandomMenno** [comment]
the [issue](https://github.com/Swatian/nexnotes/issues/2)

**Comment by derei** [comment]
@Kin69 being copied is the best flattery that is!
So, you keep doing what you've been doing so far 😁

**Comment by aRandomMenno** [comment]
> @Kin69 being copied is the best flattery that is! So, you keep doing what you've been doing so far 😁

It is kinda flattering that his work is being copied but without giving proper credit I dont respect it.

**Comment by aRandomMenno** [comment]
If he just deletes the issue I made I think we could report his github.

**Comment by aRandomMenno** [comment]
I'm not sure but it could be that [this account](https://github.com/mmarif4u) is his main account, the account he used to host nextnotes is just an alt probably.

***THIS IS MY SPECULATION!!!*** take with a grain of salt.
