### ISSUE TITLE
Display notes horizontally as rectangular boxes

### ISSUE THREAD

**Issue by serrq** [Kin69/EasyNotes#123]
A toggle placed somewhere gives the ability to switch between square and rectangular boxes so that all tastes are guaranteed.

![1000115888](https://github.com/user-attachments/assets/0edceb25-928c-48b0-93c2-1f16caa1e51d)

**Comment by Kin69** [comment]
@serrq Hello! You can already switch between square and rectangular boxes in the Settings. Just go to Settings -> Color & Styles -> Grid View. As for the option to show only the body, it has been implemented and will be available in the next update. Please stay tuned!

**Comment by Kin69** [comment]
Sorry, it only shows the title.
