### ISSUE TITLE
Biometry unlock

### ISSUE THREAD

**Issue by spageektti** [Kin69/EasyNotes#127]
Would be cool if the app could be unclocked using biometry or device password or PIN, like the proton mail app for example.

**Comment by Kin69** [comment]
Hi, I've implemented several security features in the app: Passcode, Fingerprint, and Pattern App Lock. Plus, there's a new "Lock Immediately" setting for added convenience. You can try these features right now in the nightly build, or wait until the end of the week when the update will be available on F-Droid.

**Comment by spageektti** [comment]
> Hi, I've implemented several security features in the app: Passcode, Fingerprint, and Pattern App Lock. Plus, there's a new "Lock Immediately" setting for added convenience. You can try these features right now in the nightly build, or wait until the end of the week when the update will be available on F-Droid.

Thanks!
