### ISSUE TITLE
Untranslatable strings in the Supporters List menu.

### ISSUE THREAD

**Issue by koamedev** [Kin69/EasyNotes#130]
The Supporters List menu in Settings > About has strings not translatable through Weblate.
Specifically: "Donate", "Contribution" and "Language".
There is already a 'language' string used for the settings menu, but in my opinion "Translations" would be more appropriate as credit.
![Screenshot_20240730_141021_Easy_Notes](https://github.com/user-attachments/assets/c20df7d6-0b30-4fc1-a00c-c7f635d49f2e)
![Screenshot_20240730_140923_Easy_Notes](https://github.com/user-attachments/assets/a2b27f42-33a1-465c-a675-86a208e37450)

**Comment by Kin69** [comment]
Hi @koamedev,

Thank you for raising the issue. I’ve updated the strings to be translatable.
