### ISSUE TITLE
Edit mode by default feature

### ISSUE THREAD

**Issue by PatrickHydar** [Kin69/EasyNotes#132]
It would be very convenient to have a setting called "always in edit mode" or "edit mode by default", this is because it is annoying to switch to edit mode every time you open a note, in order to edit it. off topic but I really love the app, I think this is the best of current offerings

**Comment by Kin69** [comment]
@PatrickHydar I'm glad you're enjoying the app! For the default edit mode, you can find the setting under Settings -> Behaviour -> Prioritize Editing Mode, which ensures that you always enter edit mode when clicking on a note. If you have any other preferences or need additional settings, just let me know! You can try this feature in the nightly build.
