### ISSUE TITLE
[Feature Request] Biometric Authentication option

### ISSUE THREAD

**Issue by ezpnix** [Kin69/EasyNotes#133]
here are some feature requests and suggestions: 

1. App Lock > Having an option to enable or disable the lock when entering the app. 

- A time out feature for the app lock would also be good, but you do you. If you have the time. 

2. Auto Backup > Creates an encrypted local backup, which automatically updates every day in your selected folder. 

- I kinda love how there is no cloud server to sync in, imo. The app not requiring internet permission is a breather for me. I'm fine with the ACCESS_NETWORK_STATE being there for now. 

3. Before deleting > In the encrypted vault, the same pop up where you enter your encryption passcode appears before deleting the note. 

- The alternative of this is to add a Recycle Bin feature, but what comes easier for you or what knowledge you have of it, is something I can understand completely. 

4. The titles of the notes are bold > this one is pretty much obvious ^^

5. The ability to colour customize the text in your notes > this one is quite cool if you could implement it. 

I have other suggestions, but I'll keep them inside my head for now. 

Some things I notice within the app: (I don't mind them but just wanna tell you)
- The 'continue' text when the entering password pop up appears, shows the 'e' on another line (Pretty sure it's not my phone's text size. Probably the border or margin of the text, or something like that)

![IMG_20240802_112240.png](https://github.com/user-attachments/assets/a8ee8e81-9644-4eee-b37f-7f414b35272d)

- Rename the description strings, I guess?

Still, the app is in its early dev stage, so I can understand that it will take time, but I'm willing to support your work. I don't usually make suggestions to developers nor donate to them, but when I see great potential, I just let my mind talk and act. I hope you continue developing this wonderful app, this has been my go-to since it got released. Kudos to you :]

**Comment by aRandomMenno** [comment]
Duplicate / similar to [this](https://github.com/Kin69/EasyNotes/issues/127#issue-2433075035)

**Comment by ezpnix** [comment]
> Duplicate / similar to [127](https://github.com/Kin69/EasyNotes/issues/127#issue-2433075035)

I see. I'll be deleting it then, thank you.
