### ISSUE TITLE
[BUG] APP crashes when i lounch

### ISSUE THREAD

**Issue by Stzyxh** [Kin69/EasyNotes#137]
## Required Information

- [yes ] I’m using the latest EasyNotes version
- [yes ] The device is not rooted, and nothing has been removed via ADB

### Steps to Reproduce the Bug
1. `open the app`

### Expected Behavior
The APP crashes

### Screenshots
https://github.com/user-attachments/assets/e908c6cc-e3e2-4e13-9370-2fb5be66acc7

### Smartphone Information
- **Fairphone 4** 
- **Android 13:** 
- **Nightly:** 

## crash report 
`FATAL EXCEPTION: main
Process: com.kin.easynotes, PID: 5404
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at A.L.z(Unknown Source:218)
	at W2.i.q(Unknown Source:11)
	at C3.a.v(Unknown Source:8)
	at Y3.r.u(Unknown Source:6)
	at T3.a.v(Unknown Source:22)
	at C3.a.v(Unknown Source:31)
	at T3.L.run(Unknown Source:112)
	at T3.w0.run(Unknown Source:194)
	at a4.i.run(Unknown Source:2)
	at a4.a.run(Unknown Source:91)
	Suppressed: Y3.g: [x0{Cancelling}@4516fed, Dispatchers.Main.immediate]`

**Comment by Kin69** [comment]
Please try installing the nightly build again. The issue should have been resolved about 30 minutes ago.

**Comment by Stzyxh** [comment]
> Please try installing the nightly build again. The issue should have been resolved about 30 minutes ago.

Oh thx now it works
