### ISSUE TITLE
[feature] edit files on storage

### ISSUE THREAD

**Issue by octvs** [Kin69/EasyNotes#14]
Hi there,
The app looks pretty good. However it doesn't allow editing an existing note
(afaik). Is this feature on the roadmap?

What matters is also that only not imports but updates the file inplace. This
would decouple sync & editor from each other and let user sync as they wish
(personally syncthing).

**Comment by Kin69** [comment]
Editing existing notes is available. You can click on a note and then swipe to left  or click on the top edit icon ( will be removed im new release).

Regarding your second point, would you like exported notes to be automatically updated to same path when notes are edited?

**Comment by Kin69** [comment]
To consolidate our discussions on the storage implementation for EasyNotes, we're moving this conversation to issue #9. This issue specifically addresses the editing of existing notes and the in-place update of files, which aligns with the topic at hand.
