### ISSUE TITLE
Option to not share media with gallery

### ISSUE THREAD

**Issue by serrq** [Kin69/EasyNotes#141]
Like SimpleX does. If one wants save something in gallery then he must to push "download" button below the media.

Otherwise all is private.

**Comment by Kin69** [comment]
Hi! 😊 To upload an image from your gallery to the app, simply disable Gallery Sync in the Settings > Behavior section. Then, you can safely remove the image from your gallery after uploading.

As for the Download button: currently, images are stored directly in the app's storage, so you can access them there without any extra steps.
