### ISSUE TITLE
[BUG] Arabic words doesn't appear the right way

### ISSUE THREAD

**Issue by biscuitwithtea** [Kin69/EasyNotes#145]
![IMG_20240813_011642](https://github.com/user-attachments/assets/04b8679c-c812-4473-b545-cc9391d42b49)

Letters must be combined , like تجربة instead of ت ج ر ب ة

**Comment by me-mrm** [comment]
I face same problem with Bangla writing, words are being broken after saving the note.
![Screenshot_20240814-154149](https://github.com/user-attachments/assets/6ee5a555-358f-48d8-9d95-9a4a594f5707)

**Comment by be4zad** [comment]
Also the persian text in edit mode is LTR. It must be RTL.

![Screenshot_20240821-113126_Easy Notes.png](https://github.com/user-attachments/assets/7ccaa9bf-7ba9-4385-b264-fb4d86ae63bf)

**Comment by Kin69** [comment]
Hi, thank you for your feedback! The Persian/Arabic text issue should be resolved in the nightly build release. You can test it there or wait for the official release on F-Droid. If the issue persists, please feel free to reopen this issue.
