### ISSUE TITLE
Request (Arabic + complete markdown) support

### ISSUE THREAD

**Issue by c7dl8p** [Kin69/EasyNotes#178]
### 1.Arabic support :

This compatibility is really needed, hope the dev will add it soon, arabic looks fine in editing tab but gets distorted in viewing tab, and doesn't get fixed even if I switch the lang of the app,
![Screenshot_20240917-200411](https://github.com/user-attachments/assets/c4ca7e83-2299-4d1c-9863-34d045bd3b54)
![Screenshot_20240917-200416](https://github.com/user-attachments/assets/805e690a-9076-47ca-b82e-d3b1e1c38b5c)

### 2. Complete markdown support:
The check box is not working as its working in obsidian

Easynotes :
![Screenshot_20240917-200742](https://github.com/user-attachments/assets/5dbe80b9-5305-45c1-b4d1-acf0087b1521)

Obsidian 
![Screenshot_20240917-200758](https://github.com/user-attachments/assets/728240a5-c28a-4418-800c-70d548d6695d)

####the check box is supported even in many website notes takers

#thanks for you hard work

**Comment by Chick2D** [comment]
Thank you so much I was having the same problem with Urdu (hindi also)

**Comment by Kin69** [comment]
Hi, thank you for your feedback! The Arabic text issue should be resolved in the nightly build release. You can test it there or wait for the official release on F-Droid. If the issue persists, please feel free to reopen this issue. For checkbox app doesn't support - [ ] Example but you need to use just [ ] Example
