### ISSUE TITLE
[feature] app widget

### ISSUE THREAD

**Issue by tc-tommo** [Kin69/EasyNotes#18]
I cant express how brilliant what youre doing here is! straightforward to use, simple layout, pretty UI, exactly what i've been looking for in a note app. 

I would like to see a widget for quick preview/ adding a note straight from the launcher, which is currently a key reason i'll remain with google keep for the time being.

all the best with the project! i will keep following the progress.

**Comment by Kin69** [comment]
@tc-tommo Thank you for your kind words!

I'm excited to let you know that I've implemented two widgets: one for showing a selected note and another for adding a new note. Additionally, I've added markdown support. If you'd like to try them out, you can download the [nightly build](https://github.com/Kin69/EasyNotes/raw/master/.github/nightly.png). Please note that the widget previews are still in development (just images).

Let me know if this aligns with what you had in mind or if there are any changes you'd like to see!

All the best, and thank you for following the project's progress.
