### ISSUE TITLE
[BUG] Thai language overlap when in preview mode

### ISSUE THREAD

**Issue by l2eused** [Kin69/EasyNotes#185]
## Required Information

- [x] I’m using the latest EasyNotes version
- [x] The device is not rooted, and nothing has been removed via ADB

### Steps to Reproduce the Bug
1. create any note
2. using Thai language (i.e ที่มา)
3. typing and change to preview mode

### Expected Behavior
app should overlap the top `่` and middle `ี`

### Screenshots
editing mode
![Screenshot_2024-09-27-01-06-48-081_com.kin.easynotes-edit.jpg](https://github.com/user-attachments/assets/e584c554-7985-4e87-a046-b2f875ad7b0f)

reading mode
![Screenshot_2024-09-27-01-07-11-653_com.kin.easynotes-edit.jpg](https://github.com/user-attachments/assets/e4045bcf-9974-4b2a-9070-a0133676c985)

### Smartphone Information
- **Device:** Xiaomi 14
- **OS:** Android 14
- **EasyNotes Version:** 1.3.5

**Comment by Kin69** [comment]
Hi, thank you for your feedback! The Thai language formating issue should be resolved in the nightly build release. You can test it there or wait for the official release on F-Droid. If the issue persists, please feel free to reopen this issue.
