### ISSUE TITLE
Problem in showing persian/arabic texts

### ISSUE THREAD

**Issue by RZHSSNZDH** [Kin69/EasyNotes#201]
In arabic/persian, most of letters of words have special shape in different places (start/middle/end) of a word. The application shows the letters sepirately even when the letter is in a word. So letters' shape is like when they are in the beginning of words. Of course the problem is not shown in notes' edititng mode, the problem exists only in view mode of notes.

Screenshots for more details:
![Screenshot_۲۰۲۴۱۱۰۷-۲۱۴۱۰۴_Easy_Notes](https://github.com/user-attachments/assets/5f8548d3-9d3c-48e1-b7b8-750af6bbf335)
![Screenshot_۲۰۲۴۱۱۰۷-۲۱۳۸۳۶_Easy_Notes](https://github.com/user-attachments/assets/2b5ac68b-570d-453c-8aa3-c8638cadb4e1)

**Comment by Kin69** [comment]
Hi, thank you for your feedback! The Persian/Arabic text issue should be resolved in the nightly build release. You can test it there or wait for the official release on F-Droid. If the issue persists, please feel free to reopen this issue.
