### ISSUE TITLE
Add the ability to highlight text in bold or italic

### ISSUE THREAD

**Issue by shishkevichd** [Kin69/EasyNotes#31]
The app allows writing notes using Markdown, but currently, it's not possible to highlight text in bold or italic. Please add this capability.

Best regards to the project, the best foss note app in Material You style.

**Comment by Kin69** [comment]
@shishkevichd  Hello! I've added support for bold, italic, highlight, strikethrough, and underline markdown formatting. If there are other markdown features you'd like to see, please let me know!
(U can try them in nightly build)
