### ISSUE TITLE
[Feature Request] Multilanguage with Weblate

### ISSUE THREAD

**Issue by Maell1** [Kin69/EasyNotes#32]
Hello,
You can create a page with https://hosted.weblate.org/ for the project.
Volunteers (like me) can help to translate.

:)

**Comment by Kin69** [comment]
Hello,

Thank you for the suggestion! The page for the project has already been set up. You can contribute to the translation here: [Weblate](https://hosted.weblate.org/projects/easy-notes/easy-notes-application/).

Thanks for your help!
