### ISSUE TITLE
UI/UX improvement suggestions

### ISSUE THREAD

**Issue by derei** [Kin69/EasyNotes#6]
Hi. I just stumbled on Easy Notes and I can say that I like it more than any other notes apps I tried so far. I fully understand this is the initial release and there is still a lot of work to do. Perhaps some (or maybe all) of the following suggestions are already on your ToDo list:
- when selecting list/header/markdown, the cursor should also position itself after the symbol (or in between ticks, for markdown.
- the edit/preview buttons at the top of the notes take valuable space and two buttons are redundant. Placing ot next to note's title, and instead of two buttons, having only one which toggles between edit/preview, would not only simplify the interface, but also gain more space on screen.
- "amoled colors" is rather useless if 90% of the screen (the note area) is gray. Having the most screen area "amoled black", and only accents and borders a different color, would be more beneficial.

Thank you for your work so far!

**Comment by Kin69** [comment]
Thank you so much for your kind words and for taking the time to provide feedback on Easy Notes! 

1. The issue has been addressed and resolved. Check out the fix on: https://github.com/Kin69/EasyNotes/issues/4.

2. I appreciate your perspective. However, I believe the current setup suits users' needs well.
 
3. To clarify, are you suggesting implementing the "amoled black" primarily for the home screen of the notes app, or for the editing interface itself? Is this how you envisioned it, or did you have a different idea in mind?

![issue6](https://github.com/Kin69/EasyNotes/assets/109698804/9986b38b-f20c-4d79-829e-a66c0b912f84)

**Comment by derei** [comment]
@Kin69 I was thinking of something more like this. As the user is spending most of the app time writing (is a notes app, after all), having an option for Amoled as pictured below, could prove beneficial by saving battery.
I am not saying to change the already existing Amoled theme, as many users may prefer that one. But adding an Amoled2 variant, for people (like me), would only prove beneficial. 

Regarding the interface, moving the Edit/Preview button as seen in the attachment,  and making it a toggle (when in Editing mode, buton to display the Eye - and it would switch to Preview, and when in Preview Mode, the icon would be the Pencil  - and it would switch to Editing), would achieve two things:
- larger useful screen area
- simplified interface (fewer buttons)

What do you think?

![EasyNotes (20240601013915)](https://github.com/Kin69/EasyNotes/assets/34483372/4cdbe26c-ebaf-4a70-925d-7a6891e38fd2)

**Comment by Kin69** [comment]
Your suggestions are spot on! Implementing features such as "Amoled Extreme" in version 1.2.5 could significantly improve battery life, appealing to users who value efficiency. While I appreciate the minimalist approach for Edit/Preview, I'm also attached to the current design. Perhaps I can offer it as an optional setting. Would you like it as an optional setting? Thank you for sharing your design vision!

**Comment by derei** [comment]
@Kin69 I would be more than grateful if you would be willing to add it as an optional inrerface! 🤩
Of course you should develop the app first the way you like it!

And yes, my Pixel is sucking this battery dry. I take every possible measure to save battery 😂

**Comment by Kin69** [comment]
@derei Hi, I added an Extreme AMOLED Colors option to the settings and a Minimalistic Mode. You can try them in the nightly build. Since it's "extreme," I decided to use only borders in the Edit and Home screens. Let me know if you like it as it is currently or if you want it to look like the photos.

Also, sorry for the late reply.

**Comment by derei** [comment]
@Kin69 I greatly appreciate your effort to include the requests. The outline theme looks really good. And if I may suggest to make the outline line a tad thinner, and instead of pure white, a light gray? Reason for that is the powerful brightness contrast it has against the black background. A lightweight gray would still appear as "white" to human eye, due to dynamic contrast, but it would be less striking.

The theme in the photos also had the Edit/Preview button moved from top (two buttons), to the right, inside title field, and it was suggested to work as a toggle (one button to change face, rather than two).
This current extreme theme does indeed have a way to distinguish between Edit and Preview, as one has the ⋮ and the other has ✓. However, this is far from intuitive and it can be completely missed at first, which can lead to confusion and frustration.

**Comment by Kin69** [comment]
@derei I wanted to let you know that your suggestions have been implemented! The outline theme now features a thinner outline line in a light gray shade, which improves readability without the stark contrast against the black background. Additionally, the Edit/Preview buttons have been integrated into a single toggle button within the title field for a more streamlined user experience. If there are any further improvements you'd like to see in the Extreme Amoled Theme, please let me know.

**Comment by derei** [comment]
@Kin69 you're a gem! I sent you a small token of appreciation, btw.

Speaking of further improvements, there may be few:
- enhanced markdown code ( _same as on github, for example_)
- if advanced markdown would be implemented, a "cheat card" to help with markdown symbols, which can be opened as a quick overlay if needed, would be a good addition.
- some visual differentiation for quoted text. Either a dim background, or a different font, something to distinguish it from regular text.

I would recommend against just italicizing the quoted text, because then it may be confused with regular italicized text (should advanced markdown be implemented), but a different, distinguished font. I can think of some italicized serif font, perhaps this https://www.1001fonts.com/neuton-font.html ?

- and obvuously, can't wait for a neat widget! 😁

**Comment by Kin69** [comment]
Thank you for the token of appreciation ❤️! I've been experimenting with enabling support for bold, italic, and underline simultaneously in markdown, but I haven't quite mastered it yet. Once I finish up the backup and import features, I'll shift my focus to implementing the widget.

I think implementing a different italicized font for quotes is a great idea, and I'll definitely make it happen. Thanks again for your support!
