### ISSUE TITLE
[FR] Some more text styles

### ISSUE THREAD

**Issue by DChitale** [Kin69/EasyNotes#62]
Can you add some text styles like underline, bold and italic.

Also can you add some more padding in text options bar sometimes it get misclicked .

![photo_6321170985096691065_w](https://github.com/Kin69/EasyNotes/assets/142161975/8861f6c1-9220-497e-ada3-2d9a84387c79)

Thank you great app

**Comment by Kin69** [comment]
@DChitale  Hello! I've added support for bold, italic, highlight, strikethrough, and underline markdown formatting. If there are other markdown features you'd like to see, please let me know!
(U can try them in nightly build)

**Comment by DChitale** [comment]
Thanks ,Released lastest version?

**Comment by Kin69** [comment]
Currently, New markdown is only available in the nightly build at https://github.com/Kin69/EasyNotes/releases/download/Nightly/EasyNotes-nightly.apk The new release on F-Droid is expected by the end of this week.
