### ISSUE TITLE
I don’t want to slip over the boxes body's texts when I scroll the notes

### ISSUE THREAD

**Issue by serrq** [Kin69/EasyNotes#75]
It is frustrating when I scroll the notes' list and my fingers slip on body text...

![1000114047](https://github.com/Kin69/EasyNotes/assets/113377431/548c68fb-e14f-45c5-a3ea-bd517e5d487b)

**Comment by Kin69** [comment]
Does it write anything or does it just crash?

**Comment by Kin69** [comment]
Hi,

Sorry to hear you're still having trouble with the nightly build installation. To help troubleshoot the issue, could you please:

1. If possible try installing the app using adb install <filepath> to see if that works.

2. Provide your device name and Android version, so I can attempt to replicate the problem virtually.

3. Make sure you have enabled the installation of apps from unknown sources in your settings.

4. If possible, I would be very grateful if you could provide the ADB log while attempting to install the app

5. Also I could try to send you .debug version so it would be installed as diffrent package

6. Also your last version is downloaded from f-droid or github?

**Comment by Kin69** [comment]
Ok could you try install build version from this zip file it should be installed as diffrent package https://github.com/Kin69/EasyNotes/actions/runs/9821334448/artifacts/1673867515
