### ISSUE TITLE
[Bug] Formatting Toolbar Active When Editing Title

### ISSUE THREAD

**Issue by issuant** [Kin69/EasyNotes#83]
When you're editing the title of a note, the formatting toolbar at the bottom pops up and is usable. Pressing any item on it causes it to generate content in the note area.

**Comment by Kin69** [comment]
Hello,

The formatting toolbar should only appear when the description field is focused. Could you please let me know your Android version? Additionally, can you confirm if the toolbar is visible when you are typing inside the title of a note?

Thank you.
